Adding modified terraform workflow file

diff --git a/.github\workflows/terraform.yml b/.github\workflows/terraform.yml
--- a/.github\workflows/terraform.yml
+++ b/.github\workflows/terraform.yml
@@ -31,27 +31,27 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Setup Terraform with specified version on the runner
-        uses: hashicorp/setup-terraform@v2
+      # - name: Setup Terraform with specified version on the runner
+      #   uses: hashicorp/setup-terraform@v2
 
-      - name: Terrafornm init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+      # - name: Terrafornm init
+      #   id: init
+      #   run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
       
-      - name: Terraform format
-        id: fmt 
-        run: terraform fmt -check
+      # - name: Terraform format
+      #   id: fmt 
+      #   run: terraform fmt -check
 
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
+      # - name: Terraform validate
+      #   id: validate
+      #   run: terraform validate
 
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color -input=false -out planfile
+      #   continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'fail'
-        run: exit 1
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'fail'
+      #   run: exit 1
   
